"""
Main FastAPI application for Fluxion00API.

This module provides the FastAPI application with WebSocket chat endpoints,
static file serving, and agent integration.
"""

import os
import uuid
from pathlib import Path
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse, FileResponse
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv

from src.llm import OllamaProvider
from src.agent import create_agent
from src.auth import authenticate_token, extract_token_from_query, JWTAuthError
from .websocket import ConnectionManager, websocket_endpoint

# Load environment variables
load_dotenv(override=True)

# Initialize FastAPI app
app = FastAPI(
    title="Fluxion00API",
    description="Adaptive agent framework with LLM and database access",
    version="0.0.1"
)

# CORS configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, specify exact origins
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Connection manager for WebSocket
manager = ConnectionManager()

# Get static directory path
BASE_DIR = Path(__file__).resolve().parent.parent.parent
STATIC_DIR = BASE_DIR / "src" / "static"

# Mount static files
app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")


@app.get("/")
async def root():
    """
    Serve the main chat interface.

    Returns:
        FileResponse: HTML chat interface
    """
    return FileResponse(str(STATIC_DIR / "index.html"))


@app.get("/health")
async def health_check():
    """
    Health check endpoint.

    Returns:
        dict: Health status and connection count
    """
    return {
        "status": "healthy",
        "version": "0.0.1",
        "active_connections": manager.get_connection_count()
    }


@app.get("/api/info")
async def api_info():
    """
    Get API information.

    Returns:
        dict: API information including available tools
    """
    # Create a temporary agent to get tool info
    llm = OllamaProvider()
    agent = create_agent(llm)

    return {
        "name": "Fluxion00API",
        "version": "0.0.1",
        "description": "Adaptive agent framework with LLM and database access",
        "llm_provider": "Ollama (mistral:instruct)",
        "available_tools": agent.get_available_tools(),
        "database": {
            "path": os.getenv("PATH_TO_DATABASE"),
            "name": os.getenv("NAME_DB")
        }
    }


@app.websocket("/ws/{client_id}")
async def websocket_chat(websocket: WebSocket, client_id: str):
    """
    WebSocket endpoint for chat interface with JWT authentication.

    Requires valid JWT token passed as query parameter: /ws/{client_id}?token=<jwt>

    Args:
        websocket: WebSocket connection
        client_id: Unique client identifier (generated by frontend)
    """
    # Extract token from query parameters
    query_params = dict(websocket.query_params)
    token = extract_token_from_query(query_params)

    # Authenticate token before accepting connection
    try:
        if not token:
            await websocket.close(code=4001, reason="Authentication required: missing token")
            return

        # Verify token and get authenticated user
        user = authenticate_token(token)

    except JWTAuthError as e:
        # Authentication failed - close connection with error code
        await websocket.close(code=4001, reason=f"Authentication failed: {e.message}")
        return
    except Exception as e:
        # Unexpected error during authentication
        await websocket.close(code=4000, reason=f"Authentication error: {str(e)}")
        return

    # Authentication successful - create LLM provider and agent
    llm = OllamaProvider()
    agent = create_agent(llm)

    # Handle WebSocket connection with authenticated user
    await websocket_endpoint(websocket, client_id, manager, agent, user)


@app.on_event("startup")
async def startup_event():
    """
    Application startup event handler.
    """
    print("="*60)
    print("Fluxion00API Starting...")
    print("="*60)
    print(f"Database: {os.getenv('PATH_TO_DATABASE')}/{os.getenv('NAME_DB')}")
    print(f"Ollama URL: {os.getenv('URL_BASE_OLLAMA')}")
    print(f"Static files: {STATIC_DIR}")
    print("="*60)
    print(f"Server ready! Open http://localhost:{int(os.getenv('PORT', 8000))} in your browser")
    print("="*60)


@app.on_event("shutdown")
async def shutdown_event():
    """
    Application shutdown event handler.
    """
    print("\nShutting down Fluxion00API...")
